services:
  wordpress:
    image: wordpress:6.6.2-php8.1-apache
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html # Mount the wordpress directory
      - ./:/var/www/html/wp-content/plugins/olmec-notepress # Mount the notepress directory
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_test
    ports:
      - '8080:80'
    networks:
      - wp-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_test
    ports:
      - '3306:3306'
    networks:
      - wp-network

  php:
    mem_limit: 1000mb
    memswap_limit: 1000mb
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: tail -f /dev/null
    networks:
      - wp-network
  
  wpcli:
    image: wordpress:cli-php8.1
    volumes:
      - ./wordpress:/var/www/html:delegated
    environment:
      VIRTUAL_PORT: 8080
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_test
    depends_on:
      - db
      - wordpress
    networks:
      - wp-network
  

networks:
  wp-network:
    driver: bridge